$ python -m utils.pdf_to_xml_windows
Input PDF directory: resources\pdf
Output XML directory: resources\out_xml
GROBID server does not appear up and running, the connection to the server failed
Traceback (most recent call last):
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1093, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 790, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
        sock=sock,
    ...<14 lines>...
        assert_fingerprint=self.assert_fingerprint,
    )
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 969, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
        sock=sock,
    ...<8 lines>...
        tls_in_tls=tls_in_tls,
    )
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 480, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\ssl_.py", line 524, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sock=sock,
        ^^^^^^^^^^
    ...<5 lines>...
        session=session
        ^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1076, in _create
    self.do_handshake()
    ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\ssl.py", line 1372, in do_handshake
    self._sslobj.do_handshake()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1028)

aphase@LAPTOP-3U6K5V9L MINGW64 ~/solid-state-battery-test/solid-state-battery-LLM (main)
$ python -m utils.pdf_to_xml_windows
Input PDF directory: resources\pdf
Output XML directory: resources\out_xml
GROBID server is up and running
Processing of resources\pdf\1-s2.0-S2352152X24035497-main.pdf failed with error 408 , None
Processing of resources\pdf\d4ya00138a.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S1452398123157324-main.pdf failed with error 408 , None
Processing of resources\pdf\d4ra06867j.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S2950264025000371-main.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S1385894725024593-main.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S1631074804003418-main.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S1631074804003406-main.pdf failed with error 408 , None
Processing of resources\pdf\d4sc06492e.pdf failed with error 408 , None
Processing of resources\pdf\1-s2.0-S2949736124000873-main.pdf failed with error 408 , None

PDF to XML conversion complete.

python -m utils.xml_to_json \
    --input-xml ./resources/out_xml \
    --input-xml-openalex ./resources/out_xml \
    --output-json ./resources/out_json
$ python -m utils.xml_to_json     --input-xml ./resources/out_xml     --input-xml-openalex ./resources/out_xml     --output-json ./resources/out_json
Found 10 XML files to process...
--------------------------------------------------

==============================
      Processing Summary
==============================
Total XML files found: 10
Successfully converted:  1
Rejected (license):    9
Failed (errors):       0
==============================


aphase@LAPTOP-3U6K5V9L MINGW64 ~/solid-state-battery-test/solid-state-battery-LLM (dev)
$ ./run_task_d.bash
[STEP 1] Running paper_scraping.py for years 2026 to 2027
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\paper_scraping.py", line 2, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
[STEP 2] Converting PDFs to XML using Grobid
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.
[STEP 3] Searching XML files for query: battery
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\search_query.py", line 3, in <module>
    from utils.utils import search_xml_content
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\utils.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[STEP 4] Converting XMLs to JSON
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.
[STEP 5] Correcting extracted text of JSON
garbledlist.json
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\json_correction.py", line 34, in <module>
    main(args)
    ~~~~^^^^^^
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\json_correction.py", line 18, in main
    fj.fix_json(target_filepath, output_filepath)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\fix_json_utils.py", line 351, in fix_json
    fixed_paper_json["title"] = fix_text_in_a_lump(title)
                                ~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\fix_json_utils.py", line 321, in fix_text_in_a_lump
    fixed_text = replace_garbled(text)
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\fix_json_utils.py", line 297, in replace_garbled
    wordlist: dict = json.load(f)
                     ~~~~~~~~~^^^
  File "C:\Users\aphase\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ~~~~~~~^^
UnicodeDecodeError: 'cp932' codec can't decode byte 0x8e in position 136: illegal multibyte sequence


aphase@LAPTOP-3U6K5V9L MINGW64 ~/solid-state-battery-test/solid-state-battery-LLM (dev)
$ ./run_task_d.bash
[STEP 1] Running paper_scraping.py for years 2026 to 2027
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\paper_scraping.py", line 3, in <module>
    from utils.utils import search_via_scopus, paper_info_summary, load_journals_from_json, load_checkpoint, save_checkpoint
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\utils.py", line 13, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[STEP 2] Converting PDFs to XML using Grobid
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.
[STEP 3] Searching XML files for query: battery
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\search_query.py", line 3, in <module>
    from utils.utils import search_xml_content
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\utils.py", line 13, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
[STEP 4] Converting XMLs to JSON
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1385894725024593-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1452398123157324-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1631074804003406-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1631074804003418-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2352152X24035497-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2949736124000873-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2950264025000371-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4ra06867j.grobid.tei.json にデータが保存されました。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4sc06492e.grobid.tei.json にデータが保存されました。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4ya00138a.grobid.tei.json にデータが保存されました。
[STEP 5] Correcting extracted text of JSON
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\json_correction.py", line 3, in <module>
    import utils.fix_json_utils as fj
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\fix_json_utils.py", line 1
    import re from pathlib import Path import json
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Did you mean to use 'from ... import ...' instead?


aphase@LAPTOP-3U6K5V9L MINGW64 ~/solid-state-battery-test/solid-state-battery-LLM (dev)
$ ./run_task_d.bash
[STEP 1] Running paper_scraping.py for years 2026 to 2027
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\paper_scraping.py", line 4, in <module>
    from utils.scraping import fetch_paper_content, search_openalex, fetch_pdf_content
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\scraping.py", line 4, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
[STEP 2] Converting PDFs to XML using Grobid
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\pdf_to_xml.py", line 1, in <module>
    from src.pdf_to_json.grobid_client_python.grobid_client.grobid_client import (
        GrobidClient,
    )
ModuleNotFoundError: No module named 'src'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\pdf_to_xml.py", line 1, in <module>
    from src.pdf_to_json.grobid_client_python.grobid_client.grobid_client import (
        GrobidClient,
    )
ModuleNotFoundError: No module named 'src'
[STEP 3] Searching XML files for query: battery
Searching for 10 XML files in directory 'C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\resources\out_xml'...

==============================
     Search result summary
==============================
Number of files to search: 10
Number of files that match the keyword: 10
Copied 10 files.
[STEP 4] Converting XMLs to JSON
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1385894725024593-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1452398123157324-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1631074804003406-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S1631074804003418-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2352152X24035497-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2949736124000873-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\1-s2.0-S2950264025000371-main.grobid.tei.json にデータが保存されま した。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4ra06867j.grobid.tei.json にデータが保存されました。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4sc06492e.grobid.tei.json にデータが保存されました。
C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\../resources/out_json\d4ya00138a.grobid.tei.json にデータが保存されました。
[STEP 5] Correcting extracted text of JSON
garbledlist.json
Traceback (most recent call last):
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\json_correction.py", line 34, in <module>
    main(args)
    ~~~~^^^^^^
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\json_correction.py", line 18, in main
    fj.fix_json(target_filepath, output_filepath)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aphase\solid-state-battery-test\solid-state-battery-LLM\utils\fix_json_utils.py", line 370, in fix_json
    with open(output_filepath, 'w', encoding='utf-8') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aphase\\solid-state-battery-test\\solid-state-battery-LLM\\resources\\fixed_json\\fixed_1-s2.0-S1385894725024593-main.grobid.tei.json'



$ pip install -r requirements.txt
Collecting annotated-types==0.7.0 (from -r requirements.txt (line 1))
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting anyio==4.9.0 (from -r requirements.txt (line 2))
  Using cached anyio-4.9.0-py3-none-any.whl.metadata (4.7 kB)
Collecting appnope==0.1.4 (from -r requirements.txt (line 3))
  Using cached appnope-0.1.4-py2.py3-none-any.whl.metadata (908 bytes)
Collecting asttokens==3.0.0 (from -r requirements.txt (line 4))
  Using cached asttokens-3.0.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: beautifulsoup4==4.13.4 in c:\users\aphase\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 5)) (4.13.4)
Collecting cachetools==5.5.2 (from -r requirements.txt (line 6))
  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)
Collecting certifi==2025.1.31 (from -r requirements.txt (line 7))
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting cffi==1.17.1 (from -r requirements.txt (line 8))
  Using cached cffi-1.17.1-cp313-cp313-win_amd64.whl.metadata (1.6 kB)
Collecting charset-normalizer==3.4.1 (from -r requirements.txt (line 9))
  Using cached charset_normalizer-3.4.1-cp313-cp313-win_amd64.whl.metadata (36 kB)
Collecting click==8.1.8 (from -r requirements.txt (line 10))
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting comm==0.2.2 (from -r requirements.txt (line 11))
  Using cached comm-0.2.2-py3-none-any.whl.metadata (3.7 kB)
Collecting contourpy==1.3.0 (from -r requirements.txt (line 12))
  Using cached contourpy-1.3.0-cp313-cp313-win_amd64.whl.metadata (5.4 kB)
Collecting cryptography==45.0.3 (from -r requirements.txt (line 13))
  Using cached cryptography-45.0.3-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: cycler==0.12.1 in c:\users\aphase\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 14)) (0.12.1)
Collecting debugpy==1.8.14 (from -r requirements.txt (line 15))
  Using cached debugpy-1.8.14-cp313-cp313-win_amd64.whl.metadata (1.4 kB)
Collecting decorator==5.2.1 (from -r requirements.txt (line 16))
  Using cached decorator-5.2.1-py3-none-any.whl.metadata (3.9 kB)
Collecting distro==1.9.0 (from -r requirements.txt (line 17))
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting editdistpy==0.1.5 (from -r requirements.txt (line 18))
  Using cached editdistpy-0.1.5.tar.gz (99 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting exceptiongroup==1.2.2 (from -r requirements.txt (line 19))
  Using cached exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting executing==2.2.0 (from -r requirements.txt (line 20))
  Using cached executing-2.2.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting filelock==3.18.0 (from -r requirements.txt (line 21))
  Using cached filelock-3.18.0-py3-none-any.whl.metadata (2.9 kB)
Collecting fonttools==4.58.4 (from -r requirements.txt (line 22))
  Using cached fonttools-4.58.4-cp313-cp313-win_amd64.whl.metadata (108 kB)
Collecting fsspec==2025.3.2 (from -r requirements.txt (line 23))
  Using cached fsspec-2025.3.2-py3-none-any.whl.metadata (11 kB)
Collecting google-auth==2.38.0 (from -r requirements.txt (line 24))
  Using cached google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting h11==0.16.0 (from -r requirements.txt (line 25))
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting httpcore==1.0.9 (from -r requirements.txt (line 26))
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting httpx==0.28.1 (from -r requirements.txt (line 27))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting huggingface-hub==0.30.2 (from -r requirements.txt (line 28))
  Using cached huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: idna==3.10 in c:\users\aphase\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 29)) (3.10)
Collecting importlib_metadata==8.6.1 (from -r requirements.txt (line 30))
  Using cached importlib_metadata-8.6.1-py3-none-any.whl.metadata (4.7 kB)
Collecting importlib_resources==6.5.2 (from -r requirements.txt (line 31))
  Using cached importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: inflect==7.5.0 in c:\users\aphase\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 32)) (7.5.0)
Collecting ipykernel==6.29.5 (from -r requirements.txt (line 33))
  Using cached ipykernel-6.29.5-py3-none-any.whl.metadata (6.3 kB)
Collecting ipython==8.18.1 (from -r requirements.txt (line 34))
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting jedi==0.19.2 (from -r requirements.txt (line 35))
  Using cached jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting Jinja2==3.1.6 (from -r requirements.txt (line 36))
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jiter==0.10.0 (from -r requirements.txt (line 37))
  Using cached jiter-0.10.0-cp313-cp313-win_amd64.whl.metadata (5.3 kB)
Collecting joblib==1.4.2 (from -r requirements.txt (line 38))
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting jupyter_client==8.6.3 (from -r requirements.txt (line 39))
  Using cached jupyter_client-8.6.3-py3-none-any.whl.metadata (8.3 kB)
Collecting jupyter_core==5.7.2 (from -r requirements.txt (line 40))
  Using cached jupyter_core-5.7.2-py3-none-any.whl.metadata (3.4 kB)
Collecting kiwisolver==1.4.7 (from -r requirements.txt (line 41))
  Using cached kiwisolver-1.4.7-cp313-cp313-win_amd64.whl.metadata (6.4 kB)
Collecting Levenshtein==0.27.1 (from -r requirements.txt (line 42))
  Using cached levenshtein-0.27.1-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Collecting lxml==5.4.0 (from -r requirements.txt (line 43))
  Using cached lxml-5.4.0-cp313-cp313-win_amd64.whl.metadata (3.6 kB)
Collecting MarkupSafe==3.0.2 (from -r requirements.txt (line 44))
  Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)
Collecting matplotlib==3.9.4 (from -r requirements.txt (line 45))
  Using cached matplotlib-3.9.4-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib-inline==0.1.7 (from -r requirements.txt (line 46))
  Using cached matplotlib_inline-0.1.7-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: more-itertools==10.7.0 in c:\users\aphase\appdata\local\programs\python\python313\lib\site-packages (from -r requirements.txt (line 47)) (10.7.0)
Collecting mpmath==1.3.0 (from -r requirements.txt (line 48))
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting nest-asyncio==1.6.0 (from -r requirements.txt (line 49))
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting networkx==3.2.1 (from -r requirements.txt (line 50))
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting nltk==3.9.1 (from -r requirements.txt (line 51))
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting numpy==1.26.4 (from -r requirements.txt (line 52))
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + C:\Users\aphase\AppData\Local\Programs\Python\Python313\python.exe C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d\vendored-meson\meson\meson.py setup C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d\.mesonpy-t4a5ve35 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d\.mesonpy-t4a5ve35\meson-python-native-file.ini
      The Meson build system
      Version: 1.2.99
      Source dir: C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d
      Build dir: C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d\.mesonpy-t4a5ve35
      Build type: native build
      Project name: NumPy
      Project version: 1.26.4
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]
      The following exception(s) were encountered:
      Running `icl ""` gave "[WinError 2] The system cannot find the file specified"
      Running `cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `cc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `gcc --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang --version` gave "[WinError 2] The system cannot find the file specified"
      Running `clang-cl /?` gave "[WinError 2] The system cannot find the file specified"
      Running `pgcc --version` gave "[WinError 2] The system cannot find the file specified"

      A full log can be found at C:\Users\aphase\AppData\Local\Temp\pip-install-j9i3cba5\numpy_47c0dd65b1cd44509a173defc96e616d\.mesonpy-t4a5ve35\meson-logs\meson-log.txt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


aphase@LAPTOP-3U6K5V9L MINGW64 ~/solid-state-battery-test/solid-state-battery-LLM (dev)
$ pip install -r requirements.txt
Requirement already satisfied: annotated-types==0.7.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (0.7.0)
Requirement already satisfied: anyio==4.9.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: appnope==0.1.4 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (0.1.4)
Requirement already satisfied: asttokens==3.0.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: beautifulsoup4==4.13.4 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 5)) (4.13.4)
Requirement already satisfied: cachetools==5.5.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 6)) (5.5.2)
Requirement already satisfied: certifi==2025.1.31 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 7)) (2025.1.31)
Requirement already satisfied: cffi==1.17.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 8)) (1.17.1)
Requirement already satisfied: charset-normalizer==3.4.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 9)) (3.4.1)
Requirement already satisfied: click==8.1.8 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 10)) (8.1.8)
Requirement already satisfied: comm==0.2.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 11)) (0.2.2)
Requirement already satisfied: contourpy==1.3.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (1.3.0)
Collecting cryptography==45.0.3 (from -r requirements.txt (line 13))
  Using cached cryptography-45.0.3-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: cycler==0.12.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 14)) (0.12.1)
Requirement already satisfied: debugpy==1.8.14 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (1.8.14)
Requirement already satisfied: decorator==5.2.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (5.2.1)
Requirement already satisfied: distro==1.9.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 17)) (1.9.0)
Requirement already satisfied: editdistpy==0.1.5 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 18)) (0.1.5)
Requirement already satisfied: exceptiongroup==1.2.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 19)) (1.2.2)
Requirement already satisfied: executing==2.2.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 20)) (2.2.0)
Requirement already satisfied: filelock==3.18.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 21)) (3.18.0)
Requirement already satisfied: fonttools==4.58.4 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 22)) (4.58.4)
Requirement already satisfied: fsspec==2025.3.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 23)) (2025.3.2)
Collecting google-auth==2.38.0 (from -r requirements.txt (line 24))
  Using cached google_auth-2.38.0-py2.py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: h11==0.16.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 25)) (0.16.0)
Requirement already satisfied: httpcore==1.0.9 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 26)) (1.0.9)
Collecting httpx==0.28.1 (from -r requirements.txt (line 27))
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting huggingface-hub==0.30.2 (from -r requirements.txt (line 28))
  Using cached huggingface_hub-0.30.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: idna==3.10 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 29)) (3.10)
Requirement already satisfied: importlib_metadata==8.6.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 30)) (8.6.1)
Requirement already satisfied: importlib_resources==6.5.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 31)) (6.5.2)
Collecting inflect==7.5.0 (from -r requirements.txt (line 32))
  Using cached inflect-7.5.0-py3-none-any.whl.metadata (24 kB)
Collecting ipykernel==6.29.5 (from -r requirements.txt (line 33))
  Using cached ipykernel-6.29.5-py3-none-any.whl.metadata (6.3 kB)
Collecting ipython==8.18.1 (from -r requirements.txt (line 34))
  Using cached ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: jedi==0.19.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 35)) (0.19.2)
Requirement already satisfied: Jinja2==3.1.6 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 36)) (3.1.6)
Requirement already satisfied: jiter==0.10.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 37)) (0.10.0)
Requirement already satisfied: joblib==1.4.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 38)) (1.4.2)
Collecting jupyter_client==8.6.3 (from -r requirements.txt (line 39))
  Using cached jupyter_client-8.6.3-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: jupyter_core==5.7.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 40)) (5.7.2)
Requirement already satisfied: kiwisolver==1.4.7 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 41)) (1.4.7)
Requirement already satisfied: Levenshtein==0.27.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 42)) (0.27.1)
Requirement already satisfied: lxml==5.4.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 43)) (5.4.0)
Requirement already satisfied: MarkupSafe==3.0.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 44)) (3.0.2)
Collecting matplotlib==3.9.4 (from -r requirements.txt (line 45))
  Using cached matplotlib-3.9.4-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib-inline==0.1.7 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 46)) (0.1.7)
Requirement already satisfied: more-itertools==10.7.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 47)) (10.7.0)
Requirement already satisfied: mpmath==1.3.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 48)) (1.3.0)
Requirement already satisfied: nest-asyncio==1.6.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 49)) (1.6.0)
Requirement already satisfied: networkx==3.2.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 50)) (3.2.1)
Collecting nltk==3.9.1 (from -r requirements.txt (line 51))
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: numpy==1.26.4 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 52)) (1.26.4)
Collecting openai==1.61.1 (from -r requirements.txt (line 53))
  Using cached openai-1.61.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: packaging==25.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 54)) (25.0)
Collecting pandas==2.2.3 (from -r requirements.txt (line 55))
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: parso==0.8.4 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 56)) (0.8.4)
Collecting pdfminer.six==20240706 (from -r requirements.txt (line 57))
  Using cached pdfminer.six-20240706-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: pexpect==4.9.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 58)) (4.9.0)
Requirement already satisfied: pillow==11.2.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 59)) (11.2.1)
Requirement already satisfied: platformdirs==4.3.7 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 60)) (4.3.7)
Requirement already satisfied: prompt_toolkit==3.0.51 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 61)) (3.0.51)
Requirement already satisfied: psutil==7.0.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 62)) (7.0.0)
Requirement already satisfied: ptyprocess==0.7.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 63)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 64)) (0.2.3)
Requirement already satisfied: pyasn1==0.6.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 65)) (0.6.1)
Requirement already satisfied: pyasn1_modules==0.4.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 66)) (0.4.2)
Requirement already satisfied: pycparser==2.22 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 67)) (2.22)
Requirement already satisfied: pydantic==2.11.5 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 68)) (2.11.5)
Requirement already satisfied: pydantic_core==2.33.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 69)) (2.33.2)
Requirement already satisfied: Pygments==2.19.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 70)) (2.19.1)
Requirement already satisfied: pyparsing==3.2.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 71)) (3.2.3)
Requirement already satisfied: python-dateutil==2.9.0.post0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 72)) (2.9.0.post0)
Requirement already satisfied: python-dotenv==1.0.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 73)) (1.0.1)
Requirement already satisfied: pytz==2025.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 74)) (2025.2)
Requirement already satisfied: PyYAML==6.0.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 75)) (6.0.2)
Requirement already satisfied: pyzmq==26.4.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 76)) (26.4.0)
Requirement already satisfied: RapidFuzz==3.13.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 77)) (3.13.0)
Requirement already satisfied: regex==2024.11.6 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 78)) (2024.11.6)
Requirement already satisfied: requests==2.32.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 79)) (2.32.3)
Requirement already satisfied: rsa==4.9.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 80)) (4.9.1)
Requirement already satisfied: safetensors==0.5.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 81)) (0.5.3)
Requirement already satisfied: scikit-learn==1.6.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 82)) (1.6.1)
Requirement already satisfied: scipy==1.13.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 83)) (1.13.1)
Collecting seaborn==0.13.2 (from -r requirements.txt (line 84))
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting sentence-transformers==4.1.0 (from -r requirements.txt (line 85))
  Using cached sentence_transformers-4.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six==1.17.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 86)) (1.17.0)
Requirement already satisfied: sniffio==1.3.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 87)) (1.3.1)
Requirement already satisfied: soupsieve==2.7 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 88)) (2.7)
Requirement already satisfied: stack-data==0.6.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 89)) (0.6.3)
Requirement already satisfied: sympy==1.13.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 90)) (1.13.3)
Requirement already satisfied: symspellpy==6.9.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 91)) (6.9.0)
Requirement already satisfied: tenacity==9.0.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 92)) (9.0.0)
Requirement already satisfied: threadpoolctl==3.6.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 93)) (3.6.0)
Collecting tokenizers==0.21.1 (from -r requirements.txt (line 94))
  Using cached tokenizers-0.21.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: torch==2.2.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 95)) (2.2.2)
Requirement already satisfied: tornado==6.4.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 96)) (6.4.2)
Requirement already satisfied: tqdm==4.67.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 97)) (4.67.1)
Requirement already satisfied: traitlets==5.14.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 98)) (5.14.3)
Collecting transformers==4.48.2 (from -r requirements.txt (line 99))
  Using cached transformers-4.48.2-py3-none-any.whl.metadata (44 kB)
Requirement already satisfied: typeguard==4.4.3 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 100)) (4.4.3)
Requirement already satisfied: typing-inspection==0.4.1 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 101)) (0.4.1)
Requirement already satisfied: typing_extensions==4.14.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 102)) (4.14.0)
Requirement already satisfied: tzdata==2025.2 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 103)) (2025.2)
Requirement already satisfied: urllib3==2.3.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 104)) (2.3.0)
Requirement already satisfied: wcwidth==0.2.13 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 105)) (0.2.13)
Requirement already satisfied: zipp==3.21.0 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 106)) (3.21.0)
Requirement already satisfied: colorama in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from click==8.1.8->-r requirements.txt (line 10)) (0.4.6)
Requirement already satisfied: pywin32>=300 in c:\users\aphase\appdata\local\programs\python\python312\lib\site-packages (from jupyter_core==5.7.2->-r requirements.txt (line 40)) (311)
Using cached cryptography-45.0.3-cp311-abi3-win_amd64.whl (3.4 MB)
Using cached google_auth-2.38.0-py2.py3-none-any.whl (210 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached huggingface_hub-0.30.2-py3-none-any.whl (481 kB)
Using cached inflect-7.5.0-py3-none-any.whl (35 kB)
Using cached ipykernel-6.29.5-py3-none-any.whl (117 kB)
Using cached ipython-8.18.1-py3-none-any.whl (808 kB)
Using cached jupyter_client-8.6.3-py3-none-any.whl (106 kB)
Using cached matplotlib-3.9.4-cp312-cp312-win_amd64.whl (7.8 MB)
Using cached nltk-3.9.1-py3-none-any.whl (1.5 MB)
Using cached openai-1.61.1-py3-none-any.whl (463 kB)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached pdfminer.six-20240706-py3-none-any.whl (5.6 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached sentence_transformers-4.1.0-py3-none-any.whl (345 kB)
Using cached tokenizers-0.21.1-cp39-abi3-win_amd64.whl (2.4 MB)
Using cached transformers-4.48.2-py3-none-any.whl (9.7 MB)
Installing collected packages: pandas, nltk, matplotlib, jupyter_client, ipython, inflect, huggingface-hub, httpx, google-auth, cryptography, tokenizers, seaborn, pdfminer.six, openai, ipykernel, transformers, sentence-transformers
